---
# Test application for network-delay experiment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-network-delay
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-app-network-delay
  template:
    metadata:
      labels:
        app: test-app-network-delay
    spec:
      containers:
      - name: app
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: test-app-network-delay
  namespace: default
spec:
  selector:
    app: test-app-network-delay
  ports:
  - port: 80
    targetPort: 80
---
# Chaos experiment: Network Delay
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-example
  namespace: default
spec:
  # Type of network chaos action
  action: delay  # Options: delay, loss, duplicate, corrupt, partition, bandwidth
  
  # Chaos execution mode
  mode: one  # Options: one, all, fixed, fixed-percent, random-max-percent
  
  # Target selection
  selector:
    namespaces:
      - default
    labelSelectors:
      app: test-app-network-delay
  
  # Delay configuration
  delay:
    latency: "200ms"      # Added latency
    correlation: "100"    # Correlation between successive delays (0-100)
    jitter: "50ms"        # Random variation in delay
  
  # Direction of traffic affected
  direction: to  # Options: to, from, both
  
  # Target for network chaos (optional - affects all if not specified)
  # target:
  #   selector:
  #     namespaces:
  #       - default
  #     labelSelectors:
  #       app: test-app-client
  #   mode: one
  
  # Duration - how long the chaos lasts
  duration: "2m"
