---
# Test application for pod-kill experiment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-pod-kill
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-app-pod-kill
  template:
    metadata:
      labels:
        app: test-app-pod-kill
    spec:
      containers:
      - name: app
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: test-app-pod-kill
  namespace: default
spec:
  selector:
    app: test-app-pod-kill
  ports:
  - port: 80
    targetPort: 80
---
# Chaos experiment: Pod Kill
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill-example
  namespace: default
spec:
  # Type of chaos action
  action: pod-kill
  
  # Chaos execution mode
  mode: one  # Options: one, all, fixed, fixed-percent, random-max-percent
  
  # Target selection
  selector:
    namespaces:
      - default
    labelSelectors:
      app: test-app-pod-kill
  
  # Schedule (optional - runs once if not specified)
  # scheduler:
  #   cron: "@every 2m"
  
  # Duration - how long the chaos lasts
  duration: "30s"
  
  # Grace period before killing the pod
  gracePeriod: 0
