---
# Test application for pod-failure experiment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-pod-failure
  namespace: default
spec:
  replicas: 4  # Multiple replicas to test failure handling
  selector:
    matchLabels:
      app: test-app-pod-failure
  template:
    metadata:
      labels:
        app: test-app-pod-failure
    spec:
      containers:
      - name: app
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: test-app-pod-failure
  namespace: default
spec:
  selector:
    app: test-app-pod-failure
  ports:
  - port: 80
    targetPort: 80
---
# Chaos experiment: Pod Failure
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-example
  namespace: default
spec:
  # Type of chaos action
  action: pod-failure  # Makes pod unavailable without actually deleting it
  
  # Chaos execution mode
  mode: fixed-percent
  value: "50"  # Affect 50% of matching pods
  
  # Target selection
  selector:
    namespaces:
      - default
    labelSelectors:
      app: test-app-pod-failure
  
  # Duration - how long pods remain failed
  duration: "1m"
  
  # Schedule for recurring chaos (optional)
  # scheduler:
  #   cron: "@every 5m"
