---
# Test application for stress-test experiment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-stress-test
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-app-stress-test
  template:
    metadata:
      labels:
        app: test-app-stress-test
    spec:
      containers:
      - name: app
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: test-app-stress-test
  namespace: default
spec:
  selector:
    app: test-app-stress-test
  ports:
  - port: 80
    targetPort: 80
---
# Chaos experiment: Stress Test
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: stress-test-example
  namespace: default
spec:
  # Chaos execution mode
  mode: one  # Options: one, all, fixed, fixed-percent, random-max-percent
  
  # Target selection
  selector:
    namespaces:
      - default
    labelSelectors:
      app: test-app-stress-test
  
  # Stress configuration
  stressors:
    # CPU stress
    cpu:
      workers: 2      # Number of workers
      load: 80        # CPU load percentage per worker
    
    # Memory stress
    memory:
      workers: 1      # Number of workers
      size: "256MB"   # Memory to allocate
  
  # Container to inject stress into (optional - uses first container if not specified)
  # containerNames:
  #   - app
  
  # Duration - how long the stress lasts
  duration: "2m"
