---
# Database Application - Uses admin-user ServiceAccount
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: security-demo
  labels:
    app: database
    version: v1.0.0
    team: demo-team
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
        version: v1.0.0
        team: demo-team
    spec:
      serviceAccountName: admin-user
      containers:
        - name: database
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              value: demodb
            - name: POSTGRES_USER
              value: demouser
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 999
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          emptyDir: {}

---
apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: security-demo
type: Opaque
stringData:
  password: "demo-password-123"

---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: security-demo
  labels:
    app: database
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: database
