---
# Frontend Application - Uses readonly-user ServiceAccount
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: security-demo
  labels:
    app: frontend
    version: v1.0.0
    team: demo-team
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        version: v1.0.0
        team: demo-team
    spec:
      serviceAccountName: readonly-user
      containers:
        - name: frontend
          image: nginx:alpine
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: cache
              mountPath: /var/cache/nginx
            - name: run
              mountPath: /var/run
      volumes:
        - name: nginx-config
          configMap:
            name: frontend-config
        - name: cache
          emptyDir: {}
        - name: run
          emptyDir: {}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: security-demo
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    http {
        server {
            listen 8080;
            location / {
                return 200 'Frontend Service - Calling Backend\n';
                add_header Content-Type text/plain;
            }
            location /health {
                return 200 'OK\n';
                add_header Content-Type text/plain;
            }
        }
    }

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: security-demo
  labels:
    app: frontend
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: frontend
