---
# Bind readonly-user ServiceAccount to readonly-role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: readonly-binding
  namespace: security-demo
subjects:
  - kind: ServiceAccount
    name: readonly-user
    namespace: security-demo
roleRef:
  kind: Role
  name: readonly-role
  apiGroup: rbac.authorization.k8s.io

---
# Bind developer-user ServiceAccount to developer-role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-binding
  namespace: security-demo
subjects:
  - kind: ServiceAccount
    name: developer-user
    namespace: security-demo
roleRef:
  kind: Role
  name: developer-role
  apiGroup: rbac.authorization.k8s.io

---
# Bind admin-user ServiceAccount to admin-role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-binding
  namespace: security-demo
subjects:
  - kind: ServiceAccount
    name: admin-user
    namespace: security-demo
roleRef:
  kind: Role
  name: admin-role
  apiGroup: rbac.authorization.k8s.io
